# https://travis-ci.org/kavdev/dj-stripe/
sudo: false
language: python

python: "3.6"

addons:
  postgresql: "9.4"

env:
  - TOXENV=py27-django110
  - TOXENV=py34-django110
  - TOXENV=py35-django110
  - TOXENV=py36-django110

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35-django110
  exclude:
    - python: "3.6"
      env: TOXENV=py35-django110

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox codecov

before_script:
  - psql -U postgres -c 'CREATE DATABASE "djstripe";'

script:
 - tox

after_success:
  codecov

notifications:
  email:
    on_failure: always
    on_success: change
